steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - fromgithub
  - --entry-point=helloWorld
  - --allow-unauthenticated
  - --runtime=nodejs14
  - --region=us-central1
  - --source=.
  - --trigger-http